export const ACTION_CANCELLED = "ACTION_CANCELLED";

export const SET_CONFIGS = "SET_CONFIGS";
export const SET_CONFIG = "SET_CONFIG";
export const REPLACE_CONFIG_ID = "REPLACE_CONFIG_ID";
export const DELETE_CONFIG = "DELETE_CONFIG";

export const SET_SENSORS = "SET_SENSORS";

export const SET_STREAMS = "SET_STREAMS";

export const SET_MAP_MARKERS = "SET_MAP_MARKERS";

export const FETCH_ROVER_POSITION = "FETCH_ROVER_POSITION";
